### ISSUE TITLE
Custom repository path support

### ISSUE THREAD

**Issue by yelizariev** [pre-commit/action#10]
It may be needed when custom path for checkout is used. In my case I do it because I need to checkout another repo with CI tools:

```
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: REPO
      - name: Checkout TOOLS
        uses: actions/checkout@v2
        with:
          path: TOOLS
          repository: owner/repo
          ref: master
```
So, I'd need to set path on using the action:

```
      - uses: pre-commit/action@v1.0.1
        with:
            path: REPO
```
