### ISSUE TITLE
Error: pre-commit failed with exit code 1

### ISSUE THREAD

**Issue by lpossamai** [pre-commit/action#154]
When running my Workflow, I get the following error. This happens after `pre-commit` successfully execute the necessary changes triggered by `trailing-whitespace` and the `end-of-file-fixer` hooks.

```
Error: The process '/opt/hostedtoolcache/Python/3.10.2/x64/bin/pre-commit' failed with exit code 1
```

A bit of my `pre-commit.yaml` file:

```
    - uses: actions/setup-python@v2
    - name: Execute pre-commit
      uses: pre-commit/action@v2.0.3
      env:
        SKIP: no-commit-to-branch,hadolint
      with:
        extra_args: --color=always --show-diff-on-failure --files ${{ steps.file_changes.outputs.files }}
```
