### ISSUE TITLE
Pre-commit merges changes from main branch onto PR

### ISSUE THREAD

**Issue by kunaltyagi** [pre-commit/action#157]
If I wish for pre-commit to push only  relevant changes, what should the config look like? Or do we always need to have a merge with the main branch?

Current behavior is causing confusion during PRs

Config:
```yml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```
