### ISSUE TITLE
Positional-only parameters are only supported in Python 3.8 and greater

### ISSUE THREAD

**Issue by crusaderky** [pre-commit/action#168]
The pre-commit action on https://github.com/dask/distributed has started failing with the message
```
/home/runner/.cache/pre-commit/repoz_illd_m/py_env-python3.10/lib/python3.10/site-packages/numpy/__init__.pyi:642: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```
mypy is supposedly running on Python 3.10, checking for compatibility vs. Python 3.9.

I cannot replicate the issue locally by running `pre-commit run --all-files`.
I've already tried wiping out my local `~/.cache/pre-commit`.
I've already tried changing something trivial (e.g. an already-satisfied minimum version) in .pre-commit-config.yaml in order to invalidate the github actions cache. 

.github/workflows/ci-pre-commit.yaml:
```yaml
name: Linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0
```

.pre-commit-config.yaml:
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use setup.cfg if possible instead of adding command line parameters here
        args: [--warn-unused-configs]
        additional_dependencies:
          # Type stubs
          - pandas-stubs
          - types-docutils
          - types-requests
          - types-paramiko
          - types-PyYAML
          - types-psutil
          - types-setuptools
          # Typed libraries
          - click
          - dask
          - numpy
          - pytest
          - tornado
          - zict
          - pyarrow
```

setup.cfg:
```yaml
[mypy]
python_version = 3.9
platform = linux
allow_incomplete_defs = false
allow_untyped_decorators = false
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
```
