### ISSUE TITLE
How to fix atal: could not read Username

### ISSUE THREAD

**Issue by macdrorepo** [pre-commit/action#171]
Hello,

How can I fix this:

`fatal: could not read Username for 'https://gitlab.com/': No such device or address`. 
My task looks like:
```
      - name: Pre Commit
        uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.gh_token }}
```
Token should have right permissions, it has SSO enabled (repo is private and part of organization)
