### ISSUE TITLE
Use of pre-commit.ci with dependencies

### ISSUE THREAD

**Issue by morremeyer** [pre-commit/action#180]
I'd like to switch to pre-commit.ci for the open source projects that I maintain, since that is recommended with the maintenance-only mode of this action.

Unfortunately, I could not yet find documentation on how to do so when using hooks that have additional dependencies, e.g. hadolint:

```yaml
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
```

Is there a way to do this or do we need to keep using this action for cases that need additional dependencies?

Thanks for all the work on pre-commit, it really makes maintainer life much easier ❤️
