### ISSUE TITLE
Hook fails when upgrading from ubuntu-22.04 to ubuntu-24.04

### ISSUE THREAD

**Issue by epgui** [pre-commit/action#214]
I have the following Github Actions config:

```
  check-pre-commit-hooks:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
      - name: Check other pre-commit hooks
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch,terraform_fmt
        with:
          extra_args: --all-files --show-diff-on-failure
```

This runs successfully without problem. However, when I upgrade the ubuntu version as follows...

```
  check-pre-commit-hooks:
    runs-on: ubuntu-24.04
    # ...
```

... I get the following error:

<img width="740" alt="Screenshot 2024-10-11 at 11 15 20 AM" src="https://github.com/user-attachments/assets/df7405c1-a1e4-408b-95c9-6b078aa7276a">
