### ISSUE TITLE
Action doesn't work: error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by okainov** [pre-commit/action#28]
```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pre-commit
      uses: pre-commit/action@v1.1.0
```

This doesn't work triggering error `error: invalid command 'bdist_wheel'`
