### ISSUE TITLE
hooks with entry fail in action

### ISSUE THREAD

**Issue by AdrienLemaire** [pre-commit/action#36]
I need to run `language: system` on the mypy hook in order to get it working with my project (related: https://github.com/pre-commit/pre-commit/issues/945).

As a result, Github action fails to run mypy on checks.

.pre-commit-config.yaml
```yml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        additional_dependencies: ["mypy==0.770", ...]
        language: system
        entry: env PYTHONPATH=$PYTHONPATH:app mypy
        files: \.py$
        args:
          [
            --config-file=app/mypy.ini
          ]
```

workflows/mypy.yml
```yml
name: mypy

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: mypy --all-files
```

Result:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 127

/usr/bin/env: ‘mypy’: No such file or directory
```

Do you have a suggestion to fix this issue? Or is it just not possible to run mypy on github actions using pre-commit/action in my situation?
