### ISSUE TITLE
Action failed on commit if not PR

### ISSUE THREAD

**Issue by pavel-kurnosov** [pre-commit/action#4]
Action failed because it looks like script always expect to have pull_request object available in 
`const branch = github.context.payload.pull_request.head.ref;`

**Comment by asottile** [comment]
this is intentional, the `push` functionality (which guards that particular line) is only intended for `pull_request` workflows

what would it do otherwise?

**Comment by pavel-kurnosov** [comment]
It was running on normal commits to master. After I removed from your example file line:
`  push:
    branches: [master]
`
All was fine.

**Comment by asottile** [comment]
can you show your action?

**Comment by pavel-kurnosov** [comment]
Sure:
`
name: pre-commit

on:
  pull_request:
  push:
    branches: [master] # action fails without PR because of the bug.

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: set PY
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
`
This version failed on commit when there were changes.

**Comment by asottile** [comment]
ok, that sounds expected -- the autofixing behaviour is only for pull requests

**Comment by pavel-kurnosov** [comment]
Now I see :)  I was just thinking that action should not fail if it is running not in PR. Maybe if should -- then with an error saying what is the problem.

**Comment by asottile** [comment]
can you try with v1.0.1 -- I moved some of the code around to maybe make it not error? b25e7c29f3ab5d643ab171551faebb9525feec7b

**Comment by pavel-kurnosov** [comment]
Now I got another error:
`##[error]The process '/opt/hostedtoolcache/Python/3.8.0/x64/bin/pre-commit' failed with exit code 1
##[error]Node run failed with exit code 1
`

**Comment by asottile** [comment]
perfect, that's exactly working as intended -- thanks for the help testing it!

**Comment by vtrokhymenko** [comment]
hi
sorry, maybe u know how fixed this error?
![image](https://user-images.githubusercontent.com/8581044/74145355-425b8e80-4c07-11ea-861b-382066383bed.png)

**Comment by vtrokhymenko** [comment]
also, why in this line `failed`?
![image](https://user-images.githubusercontent.com/8581044/74145621-fc52fa80-4c07-11ea-8e61-5f944decc9e4.png)

**Comment by asottile** [comment]
it tells you why it failed:

```
- files were modified by this hook
```

also just below that should be the list of files that changed

and tells you how to reproduce it (not shown, but if you scroll down):

```
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
```

**Comment by vtrokhymenko** [comment]
thx

also, why i always get this error?
![image](https://user-images.githubusercontent.com/8581044/74172395-d6921980-4c38-11ea-881f-95ed7871442d.png)

**Comment by asottile** [comment]
that's probably fallout from virtualenv 20.x CC @gaborbernat

**Comment by gaborbernat** [comment]
Do you have the virtualenv creation log?

**Comment by vtrokhymenko** [comment]
> Do you have the virtualenv creation log?

at this part `Run actions/checkout@v2`?

**Comment by asottile** [comment]
@vtrokhymenko if you link instead of screenshot that will help all of us, right now it's pretty hard to help you

**Comment by vtrokhymenko** [comment]
@asottile i run this at the private repo
which part of you pre-commit send u?

**Comment by vtrokhymenko** [comment]
i use this example

```
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.1
```

**Comment by vtrokhymenko** [comment]
for `.pre-commit-config.yaml` use next

```
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config
        files: \.py$
        exclude: ./fastText/*

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        files: \.py$
        exclude: ./fastText/*

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
      exclude: (.?)pre-commit((-config)?)\.y(a?)ml # pre-commit.yml & .pre-commit-config.yaml
    - id: end-of-file-fixer
      exclude: (.?)pre-commit((-config)?)\.y(a?)ml # pre-commit.yml & .pre-commit-config.yaml
    - id: requirements-txt-fixer

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        args: ['--ignore=E501,W292','--max-line-length=120']
        files: \.py$
        exclude: ./fastText/*

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: ['--line-length=120','--skip-string-normalization']
        files: \.py$
        exclude: ./fastText/*
```

**Comment by vtrokhymenko** [comment]
more at the picture

![image](https://user-images.githubusercontent.com/8581044/74173821-7e104b80-4c3b-11ea-965a-fb843bd78a46.png)

**Comment by asottile** [comment]
@gaborbernat I bet I know what's happening -- the changes in virtualenv 20 will break anyone that's doing similar :( -- caching a virtualenv directory is now insufficient as it symlinks to `~/.local/...` for setuptools / pip / ...

**Comment by gaborbernat** [comment]
Yeah, if you want to avoid that just use ``--seed pip`` to not use the ``app-data`` seed mechanism.

**Comment by asottile** [comment]
do we expect everyone in the community to adjust for that? this is going to break a lot of stuff, including pre-commit

**Comment by vtrokhymenko** [comment]
i can't understand how to use `--seed pip` true & where?

**Comment by gaborbernat** [comment]
Yeah. I'd expect CI environments that can't cache app-data to set seed=pip within a global ``virtualenv.ini``. Or tools 🤔 switching to that mechanism within CI.

**Comment by asottile** [comment]
it might make sense to make that an option and not the default, at least for virtualenv 20

**Comment by gaborbernat** [comment]
It's already an option via the ``--seed pip`` flag. I do think it should be the default; as excluding all CIs that cache badly that's the most value.

**Comment by asottile** [comment]
the problem is it breaks all _existing_ caching strategies, not just mine

**Comment by vtrokhymenko** [comment]
> It's already an option via the `--seed pip` flag. I do think it should be the default; as excluding all CIs that cache badly that's the most value. If pre-commit does not agree you're free to set the `VIRTUALENV_SEED=pip` environment variable to override this.

ok, and how to do this? where and what i should update?

**Comment by asottile** [comment]
they should also probably be hardlinks and not symlinks -- blowing away appdata should not break running applications

**Comment by vtrokhymenko** [comment]
btw, but sometimes they ran without error

**Comment by asottile** [comment]
@gaborbernat there's also no way that I can find to cache two directories at once in either azure pipelines nor github actions -- so I don't know how someone _could_ do this "correctly"

**Comment by gaborbernat** [comment]
I agree this is a valid issue; however, I think it's an issue at CI level, rather than end-user level.  At the moment you can move the application data folder location via the ``_VIRTUALENV_OVERRIDE_APP_DATA`` env-var... to be within that single folder. Might make it public for this use-case, so strip the underscore from the start of that name.

**Comment by asottile** [comment]
the user doesn't have control over the `virtualenv` command in many cases (for example `tox`, `pre-commit`, etc. invoke it on behalf of the user)

I think a more coordinated rollout with CI providers might be in order (they put that file in place, then virtualenv defaults to that value -- not the other way around where people are broken until then)

**Comment by gaborbernat** [comment]
The user have control over environment variables within CIs; setting the environment variable ``VIRTUALENV_SEED=pip`` will solve the issue for anyone doing caching.

**Comment by asottile** [comment]
I understand the major version bumped, but breaking a major usecase of a tool which is as widespread in usage as virtualenv should not be taken lightly -- in my opinion rolling back that particular change, adding an opt in, and then gradually changing the landscape before breaking it would be a much better rollout strategy

**Comment by gaborbernat** [comment]
@asottile it's not entirely breaking a use case; I've enumerated two workarounds at least above; either opting for ``pip`` seeder or moving the app-data within the cached folder will suffice. Both are doable by either the end-user or the tool that's broken by it.

**Comment by asottile** [comment]
right but now *everyone needs to do that*

**Comment by gaborbernat** [comment]
Realistically talking this is the best day to introduce this change (a new non-backwards compatible major release has been just done), as it will be just as breaking a year down the line. People will keep ignoring to migrate until they're not broken by it is just the fact of life. Not everyone, just who uses cache mechanisms in a CI (I think we can agree that's probably a lot less than the number of users using it locally). Would be just as much **everyone needs to do that** (a lot more) if people would need to manually enable this locally on their DEV machine. 

If you find many pre-commit users complain about this you're free to either pin virtualenv, or pass from within the tool the seed pip flag; to fix the issue for all your users. Though IMHO I'd rather escalate the issue into the CIs.

**Comment by asottile** [comment]
but if it's not enabled now, we have the opportunity to get CI providers to update before breaking it

**Comment by gaborbernat** [comment]
IMHO I'm not aware of this channel that all CI providers would follow, and act on. Who was interested had at least two weeks to try out the new beta, as did the Datadog people (see https://github.com/DataDog/integrations-core/pull/5617). Similarly, not sure how long timeframe would be just enough to give them a realistic opportunity to change. The very least reverting this change would be breaking to the current behaviour we promise with ``20.0.0``, so I'd rather not. If really needed would instead pin tox/pre-commit virtualenv to use old, and reach out on this channel to give such CI providers the opportunity. In the meantime, I'd encourage the few users that cache their CI to use the ``VIRTUALENV_SEED=pip`` workaround, and yes for everyone who gets bitten by it. Let's see for how many people this becomes an issue. I think given the major release such breaking change is acceptable, and many people seem happy with the faster out of box virtual environment creation times this buys us; so there's the trade-off.

**Comment by asottile** [comment]
there's no docker image here to change, it's just a script which runs `pre-commit` -- it can't be "fixed" for people

**Comment by gaborbernat** [comment]
As I see you can use https://help.github.com/en/actions/reference/development-tools-for-github-actions#set-an-environment-variable-set-env to set an env-var in the example description of the README; and yes everyone needs to do it, but that's the price to pay for copying scripts from places. You'll have to spend time to maintain it.

**Comment by vtrokhymenko** [comment]
so, at this moment u can't fix this problem?

**Comment by asottile** [comment]
I can't but you can apply the `VIRTUALENV_SEED=pip` hack to your configuration to maybe work around it -- you'll probably need to bump the cache version as well (probably by changing `key: pre-commit|` to `key: pre-commit2|` or something of the sort)

**Comment by vtrokhymenko** [comment]
> I can't but you can apply the `VIRTUALENV_SEED=pip` hack to your configuration to maybe work around it -- you'll probably need to bump the cache version as well (probably by changing `key: pre-commit|` to `key: pre-commit2|` or something of the sort)

like this:

```
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
    - name: change virtualenv seed
        run: VIRTUALENV_SEED=pip
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.1
```

or 

```
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.1
```
?
