### ISSUE TITLE
Conflict between local pre-commit and github/action pre-commit

### ISSUE THREAD

**Issue by elmerehbi** [pre-commit/action#47]
Locally, pre-commit passes just fine, however it fails with Github actions. `black`  is reformatting on using github actions differently than on my machine. Any idea why that would be?

For the record, I already have

`.pre-commit-config.yml`
```
# https://pre-commit.com | https://pre-commit.com/hooks.html

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
        - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
        - id: detect-private-key
        - id: trailing-whitespace
          types: [python]
        - id: check-yaml
        - id: check-added-large-files
          args: ['--maxkb=1024']
        - id: check-docstring-first
        - id: end-of-file-fixer
          types: [python]
        - id: name-tests-test
        - id: flake8
```
`pyproject.toml`
```
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
```

`.github/workflows/pre-commit.yaml`
```
name: pre-commit

on:
  pull_request:
  push:
    branches: [<branch-name>]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
```

What am I missing?
