### ISSUE TITLE
Run on changed files, how?

### ISSUE THREAD

**Issue by s0undt3ch** [pre-commit/action#48]
How would I run this action but only for changed files on a pull request?

**Comment by s0undt3ch** [comment]
To answer myself, using another action.
```yaml

    - id: changed-files
      name: Get Changed Files
      uses: jitterbit/get-changed-files@v1
    - name: List Changed Files
      run: |
        for changed_file in ${{ steps.changed-files.outputs.all }}; do
          echo "${changed_file}"
        done
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: --files ${{ steps.changed-files.outputs.all }}
```
