### ISSUE TITLE
Python version problem

### ISSUE THREAD

**Issue by jdkandersson** [pre-commit/action#52]
Hi,

Good work, thanks for putting this together as well as pre-commit!

I started using this action and ran into a problem related to a python version. In the readme the following configuration is proposed:
```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
```

This caused some error for me related to that python 3.7 wasn't available. The following configuration fixed it:
```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
       with:
        python-version: 3.7
    - uses: pre-commit/action@v2.0.0
```

The only problem with it is that now it runs on python 3.7
