### ISSUE TITLE
Not pushing back fixes on private repo

### ISSUE THREAD

**Issue by marcelotrevisani-imgtec** [pre-commit/action#57]
Hi folks,

First of all, thank you very much for the ``pre-commit``! I really like to use it :)

The problem I am facing is that, I have a self-hosted machine for my private repository, it runs normally and it will accuse the problems, but it is not fixing the errors as it is mentioned on the docs. Maybe I am missing something, sorry if it is the case.

That is my yaml for pre-commit:
```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

and my ``.pre-commit-config.yaml`` is:
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: sort-simple-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args: [--autofix]
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.2.2
    hooks:
        -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        exclude: tests/data
        language_version: python3
        additional_dependencies:
            - flake8-typing-imports==1.9.0
            - flake8-builtins==1.5.3
            - flake8-bugbear==20.1.4
            - flake8-isort==3.0.1

```

Do you need any more information?
