### ISSUE TITLE
use with private hook

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [pre-commit/action#66]
I'm trying to use this with a private custom hook, our .pre-commint-config.yaml looks something like
```
repos:
  - repo: git@github.com:somehwere_private.git
```
In the action I've got:
```
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

But I get
```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
```

Changing config to use HTTP:
```
repos:
  - repo: https://github.com/somewhere_private.git
```

results in
```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com': No such device or address
```
