### ISSUE TITLE
Usage of this GitHub action together with the GitHub action from psf/black

### ISSUE THREAD

**Issue by famura** [pre-commit/action#68]
Dear pre-commit devs,

I want to use your GitHub action action in my projects workflow together with the python code linter Black.

So far, I managed to make pre-commit work with the Black GitHub action as described in their doc (https://github.com/psf/black#github-actions).  However, as far as I understand, this requires installing pre-commit on every machine. My desired scenario is having both action run (after each other?) such that this process is abstracted away from my co-workers.

At the moment, I have a `.pre-commit-config.yaml` file in the root directory, as well as a `black.yml` and `pre-commit.yml` in the`.github/workflows` directory

.pre-commit-config.yaml
```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
```

pre-commit.yml
```
name: Run pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
```

Unfortunately the action crashes (see attrached image). What am I missing / doing wrong?
![GitHub Action Run](https://user-images.githubusercontent.com/37794142/101738898-17f88d00-3ac7-11eb-9039-d608368b2bd9.png)
