### ISSUE TITLE
Setting pre-commit GH action to only run for files that have changed

### ISSUE THREAD

**Issue by BwL1289** [pre-commit/action#7]
Hi Anthony,

Regarding https://pre-commit.com/#usage-in-continuous-integration, if i only want my action to check files which have changed, how would i incorporate the following?

`pre-commit run --origin HEAD --source origin/HEAD`

thanks,
Ben

**Comment by asottile** [comment]
there isn't an option currently but one might be a good idea. I'm currently trying to rehaul this without GA (due to the limitations) and that's a planned feature there

a PR here would be appreciated if you want to work on such a thing

note that it would have to be an option since there are cases where modifying a file can cause failures in other files (such as with mypy) and often CI is a better guard to run against all files

**Comment by BwL1289** [comment]
got it—thanks so much! won't be able to work on a PR (as I don't know JS), but will definitely check back for updates. thanks again for all of your awesome work.

**Comment by deepyaman** [comment]
Hi guys! I didn't see this issue, but I needed this functionality today and found a way around it. #15 is the modified action I used, in conjunction with https://github.com/futuratrepadeira/changed-files. See my the relevant part of my `steps` config below:

```yaml
    - name: Changed Files Exporter
      uses: futuratrepadeira/changed-files@v3.0.0
      id: changed-files
      with:
        repo-token: ${{ github.token }}
    - name: set FILES
      run: |
        echo "::set-env name=FILES::${{ steps.changed-files.outputs.files_created }} ${{ steps.changed-files.outputs.files_updated }} ${{ steps.changed-files.outputs.files_deleted }}"
    - uses: deepyaman/action@v1.0.2
      with:
        args: --files ${{ env.FILES }}
        token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by asottile** [comment]
would `args: --from-ref origin/HEAD --to-ref HEAD` work as well (instead of needing `changed-files`)? -- that's mostly what this issue is about

**Comment by deepyaman** [comment]
> would `args: --from-ref origin/HEAD --to-ref HEAD` work as well (instead of needing `changed-files`)? -- that's mostly what this issue is about

The args get passed as expected, but the refs aren't found. I can do `--to-ref ${{ github.ref }}`, which returns `remotes/pull/10/merge`, but not sure how to get `origin/HEAD`.

Running `git branch -a` in a previous step to test doesn't yield any other branches:

```bash
Run git branch -a0s
  remotes/pull/10/merge
Run git branch -a
* (HEAD detached at pull/10/merge)
  remotes/pull/10/merge
```

Maybe you'd have to have another checkout step, but I'm not sure...

**Comment by deepyaman** [comment]
I'm no expert on GitHub Actions (first tried it yesterday afternoon), but I'm inclined to say you can't access references/branches that naively. I did a lot of googling for finding the list of files that changed in Actions, but didn't find any straightforward `git` command; e.g.:

* https://github.com/futuratrepadeira/changed-files/blob/master/src/main.ts uses GitHub APIs
* https://github.com/lots0logs/gh-action-get-changed-files/blob/master/main.js also uses GitHub APIs (I tried this, and it didn't work for me, but I could have been doing something wrong at that point)
* https://github.com/nholden/modified-file-filter-action/blob/master/bin/entrypoint parses the push event (I didn't try this Action)

I wrote #15 because I wanted to be able to specify different args (not just changed files), and I used it to support the use case in this issue with other actions, but I agree that it would be great to make a more convenient way to run on changed files only as it's a documented common use case.

**Comment by jirikuncar** [comment]
@BwL1289 please check #17. I have added job inputs `source` and `origin`. There is also an example how you can use it with commit shas.

**Comment by asottile** [comment]
#15 provides a way to do this

**Comment by dmateusp** [comment]
Hey, thought I'd share another example of using this feature:

```yaml
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --files ${{ steps.file_changes.outputs.files}}
```

**Comment by spaghEddieDoyle** [comment]
> Hey, thought I'd share another example of using this feature...

thanks! but please note that you should now use this due to https://github.com/trilom/file-changes-action/issues/81

```yaml
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: 'space'  # no longer ' '
```

**Comment by RayBB** [comment]
If you want it to run for all files changed for the whole pull request (not just most recent commit) you'll want to follow this:
https://github.com/trilom/file-changes-action/issues/96#issuecomment-1016523548

```
name: pre-commit
on:
  pull_request
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        prNumber: ${{ github.event.number }}
        output: ' '
    - uses: pre-commit/action@v2.0.3
      name: mypy
      with: 
        extra_args: mypy --files ${{ steps.file_changes.outputs.files }}
```

**Comment by kuisathaverat** [comment]
This snippet will use the base commit from the target branch (e.g. origin/main) and the latest commit of the PR.
 
```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # requites to grab the history of the PR
          fetch-depth: 0 
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
```

**Comment by jpmckinney** [comment]
Given that https://github.com/trilom/file-changes-action seems unmaintained and is using Node 12 and doesn't use set-output, which GitHub will be deprecating and/or disabling, new steps can be:

```
      - id: changed-files
        uses: tj-actions/changed-files@v36
      - uses: pre-commit/action@v3.0.0
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          extra_args: pip-compile --files ${{ steps.changed-files.outputs.all_changed_files }}
```

Or whatever your `extra_args` are.

On `push` the https://github.com/tj-actions/changed-files action compares to last commit. On `pull_request` it compares to  the base branch (see readme).

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
