### ISSUE TITLE
Action fails to install pre-commit

### ISSUE THREAD

**Issue by JamesWoolfenden** [pre-commit/action#78]
Hi 
I get the error:
Error: Unable to locate executable file: pre-commit, when i run pre-commit action.

The action seems fails to install pre-commit
https://github.com/JamesWoolfenden/terraform-aws-athena/runs/1848456616?check_suite_focus=true#step:3:1

Python is set to 3.8 but seems to install using pip and not pip3?
GHA config:

```yaml
 security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v2.0.0
```
  any help would be appreciated.
